// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbDuVlKJ62TUlWIdTABLa5iMKbXYELytg',
    appId: '1:633321115368:web:67e78783dc572ad2c0035d',
    messagingSenderId: '633321115368',
    projectId: 'ecommerce-app-2bc1e',
    authDomain: 'ecommerce-app-2bc1e.firebaseapp.com',
    storageBucket: 'ecommerce-app-2bc1e.firebasestorage.app',
    measurementId: 'G-6WLW7S67W4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0zy_Ajpr5F41pIV3bQXQN84F5GEbx3_M',
    appId: '1:633321115368:android:2872ebdaad46c911c0035d',
    messagingSenderId: '633321115368',
    projectId: 'ecommerce-app-2bc1e',
    storageBucket: 'ecommerce-app-2bc1e.firebasestorage.app',
  );
}
